CXXFLAGS=-g -I../
CC=g++

OBJ=$(patsubst %,%.o,$(BIN))
SRC=$(patsubst %,%.cpp,$(BIN))

all:$(BIN)

$(BIN):$(OBJ) ../util/util.o

$(OBJ):$(SRC) ../include/data.h ../util/util.h 

%.o:%.cpp
	$(CC) $(CXXFLAGS) -c -o $@ $<

clean:
	rm -rf $(BIN) *.o
